version: '3'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: 'Europe/Paris'
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database
