name: CD
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deployment:
    name: "🚀 - Deploy"
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            npm ci

            # Build the API
            node ace build --production
            cp .env build/.env
            cd build
            npm ci --production

            # Run migrations & seeds
            node ace migration:run --force
            #node ace db:seed --force

            # Restart server 
            pm2 delete api-vision
            pm2 start server.js --name api-vision
