name: Build, test and deploy
on:
  repository_dispatch:
    types: [ci_cd]

jobs:
  tests:
    name: "🧪 - Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13"
          postgresql db: vision_test

      - run: npm ci
      - run: npm run coverage
        env:
          HOST: 0.0.0.0
          NODE_ENV: testing
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USER:
          PG_PASSWORD:
          PG_DB_NAME: vision_test
          APP_KEY: random
          DRIVE_DISK: local
          DB_CONNECTION: pg

  deployment:
    if: github.event_name != 'pull_request'
    name: "🚀 - Deploy"
    runs-on: ubuntu-latest
    needs: [tests]
    environment:
      name: production
      url: "https://api.vision-data.io"

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            npm ci

            # Build the API
            node ace build --production --ignore-ts-errors
            cp .env build/.env

            # Build the API documentation
            node ace swagger:generate && cp -a docs/ build/docs

            # Install dependencies for build
            cd build
            npm ci --production

            # Run migrations & seeds
            node ace migration:run --force
            #node ace db:seed --force

            # Restart server 
            pm2 delete api-vision
            pm2 start server.js --name api-vision
